info:
  description: Spring Cloud Samples
  url: https://github.com/spring-cloud-samples
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
foo: from foo development
democonfigclient:
  message: hello from dev profile
my:
  prop: from application-dev.yml
bar: spam
